### ISSUE TITLE
Missing method is throwing a warning

### ISSUE THREAD

**Issue by johnalarcon** [ozfiddler/sc-utility#2]
In the plugin's settings page, there's a warning notice. This notice will be hidden if debugging is not enabled, but should be addressed to avoid inflated error logs.

### Description
The cause of the warning is found at [line 165](https://github.com/ozfiddler/sc-utility/blob/1ad8df549861226f2555222a46a07c813abf869b/sc-utility.php#L165). The `print_section_info` method does not exist in the class.

```
 Warning: call_user_func() expects parameter 1 to be a valid callback, class 'MySettingsPage' does not have a method 'print_section_info' in C:\xampp\htdocs\codepotent\cpress\wp-admin\includes\template.php on line 1342
```

**Comment by ozfiddler** [comment]
Thank John. I had deleted those calls elsewhere but missed that particular instance. Now fixed and that will go through in next version. Cheers.
